// import Link from "next/link";
// import contenData from "../../../data/AboutConten";
// import { FaChevronRight } from "react-icons/fa";

// export async function generateMetadata({ params }) {
//   return {
//     title: 'About Conten Details Page',
//     description: "Generated by create About Page",
//   }
// }

// export async function generateStaticParams() {
//   const contenId = contenData.map((conten) => ({ id: conten.id.toString() }));
//   return contenId;
// }

// const AboutContenDetailsPage = ({ params }) => {
//   const contenItem = contenData.find((item) => item.id == params.id);

//   if (!contenItem) {
//     return <div>Content not found</div>;
//   }

//   return (
//     <div>
//        <div className="relative w-full">
//         <img
//           src="/img/bg.jpg"
//           alt=""
//           className="h-[430px] w-full object-cover"
//         />
//         <div className="py-4 flex justify-center items-center gap-4 px-5 absolute inset-0 flex justify-center items-center text-white text-2xl font-bold">
//           <div>
//             <Link href="/" className="hover:text-[#F68921] pt-2">
//               Home
//             </Link>
//           </div>
//           <div>
//             <FaChevronRight />
//           </div>
//           <div>
//             <Link href="/aboutconten" className="hover:text-[#F68921] pt-2">
//              About Conten
//             </Link>
//           </div>
//           <FaChevronRight />
//           <div>
//             <Link href={`#`} className="text-[#F68921] pt-2">
//              Conten Details
//             </Link>
//           </div>
//         </div>
//       </div>
//       <h1>{contenItem.title}</h1>
//       <p>{contenItem.description}</p>
//       {
//         contenItem.sections.map((item,id)=>{
//           <h1 key={id}>{item.heading}</h1>
//         })
//       }
//     </div>
//   );
// };

// export default AboutContenDetailsPage;





import Link from "next/link";
import contenData from "../../../data/AboutConten";
import { FaChevronRight } from "react-icons/fa";

export async function generateMetadata({ params }) {
  return {
    title: 'About Content Details Page',
    description: "Generated by create About Page",
  }
}

export async function generateStaticParams() {
  const contenId = contenData.map((conten) => ({ id: conten.id.toString() }));
  return contenId;
}

const AboutContenDetailsPage = ({ params }) => {
  const contenItem = contenData.find((item) => item.id == params.id);

  if (!contenItem) {
    return <div>Content not found</div>;
  }

  return (
    <div>
      <div className="relative w-full">
        <img
          src="/img/bg.jpg"
          alt=""
          className="h-[430px] w-full object-cover"
        />
        <div className="py-4 flex justify-center items-center gap-4 px-5 absolute inset-0 text-white text-2xl font-bold">
          <div>
            <Link href="/" className="hover:text-[#F68921] pt-2">
              Home
            </Link>
          </div>
          <div>
            <FaChevronRight />
          </div>
          <div>
            <Link href="/aboutconten" className="hover:text-[#F68921] pt-2">
              About Content
            </Link>
          </div>
          <FaChevronRight />
          <div>
            <Link href="#" className="text-[#F68921] pt-2">
              Content Details
            </Link>
          </div>
        </div>
      </div>
      <div className="px-5 py-10 bg-slate-100">
        <h1 className="text-3xl font-bold text-center text-[#F68921] px-5">{contenItem.title}</h1>
        <p className="mt-4 px-5 py-5 text-xl">{contenItem.description}</p>
        {contenItem.sections.map((item, id) => (
         
         <section key={id} class="text-gray-600 body-font overflow-hidden">
           <div class="container px-5 py-10 mx-auto">
             <div class="-my-8 divide-y-2 divide-gray-100">
           
               <div class="py-8 flex flex-wrap md:flex-nowrap">
                 <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                   <span class="font-semibold title-font text-[#F68921]">{item.category}</span>
                   <span class="text-sm text-gray-500">{item.date}</span>
                 </div>
                 <div class="md:flex-grow">
                   <h2 class="text-2xl font-medium text-gray-900 title-font mb-2">{item.heading}</h2>
                   <p class="leading-relaxed">{item.content}</p>
                 
                 </div>
               </div>
             </div>
           </div>
         </section>
        ))}
      </div>
    </div>
  );
};

export default AboutContenDetailsPage;
