
import AboutCard from '@/components/AboutCard';
import AboutHeader from '@/components/AboutHeader';
import Numbers from '@/components/Number';
import TeamMember from '@/components/Team';
import React from 'react';
// or Dynamic metadata
export async function generateMetadata({ params }) {
  return {
    title: 'About Page',
    description: "Generated by create About Page",
  }
}
const AboutPage = () => {
  return (
    <div>
      <AboutHeader/>
      <AboutCard/>
      <TeamMember/>
      <Numbers/>
    </div>
  );
};

export default AboutPage;
