import PortfolioCard from "@/components/ProtfolioCard";
// or Dynamic metadata
export async function generateMetadata({ params }) {
    return {
      title: 'Protfolio Page',
      description: "Generated by create Protfolio Page",
    }
  }

const ProtfolioPage=()=>{
    return(
        <div>
            <PortfolioCard/>
        </div>
    )
}
export default ProtfolioPage;