

import RichContents from "@/components/RichConten";
import ServiceCard from "@/components/ServiceCard";
import ServiceHeader from "@/components/ServiceHeader";
// or Dynamic metadata
export async function generateMetadata({ params }) {
  return {
    title: 'Service Page',
    description: "Generated by create Service Page",
  }
}

const ServicePage=()=>{
return(
<div>
  <ServiceHeader/>
  <RichContents/>
  <ServiceCard/>
</div>
)
}
export default ServicePage;


