import ServiceDetails2 from "@/components/ServiceDetail";
import serviceData from '@/data/serviceData';  

export async function generateStaticParams() {
  const ids = serviceData.map(service => ({ id: service.id.toString() }));
  return ids;
}

export async function generateMetadata({ params }) {
  return {
    title: 'Service Details Page',
    description: "Generated by create About Page",
  }
}
const ServiceDetailsPage = () => {
  return (
    <ServiceDetails2/>
  );
};

export default ServiceDetailsPage;
