import Contact from "@/components/Contact";
import Link from "next/link";
import { FaChevronRight } from "react-icons/fa6";
// or Dynamic metadata
export async function generateMetadata({ params }) {
  return {
    title: 'Contact Page',
    description: "Generated by create Contact Page",
  }
}
const ContactPage=()=>{
    return(
        <div>
             <div>
            <div className="relative w-full sm:pb-10">
        <img
          src="/img/bg.jpg"
          alt=""
          className=" sm:h-[430px] w-full object-cover"
        />
        <div className="py-4  gap-4 px-5 absolute inset-0 flex justify-center items-center text-white text-md sm:text-2xl font-bold">
          <div>
          <Link href="/" className="hover:text-[#F68921] pt-2">
              Home
            </Link>
          </div>
          <div>
            <FaChevronRight />
          </div>
          <div>
          <Link href="/contact" className="text-[#F68921] pt-2">
              Contact
            </Link>
          </div>
        </div>
      </div>
            <Contact/>
         </div>
            
        </div>
    )
}
export default ContactPage;