// import { IoShieldCheckmark } from "react-icons/io5";
// import tabs from '../../../data/MobileViewDomain';
// import Image from "next/image";
// export async function generateMetadata({ params }) {
//     return {
//       title: 'Product Page',
//       description: "Generated by create Service Page",
//     }
//   }
// export async function generateStaticParams() {
//     const contenId = tabs.map((tab) => ({ id: tab.id.toString() }));
//     return contenId;
//   }
// const DomainDetailsMobileViewPage = ({params}) => {

//     const contenItem = tabs.find((item) => item.id == params.id);

//     if (!contenItem) {
//       return <div>Content not found</div>;
//     }
//     return (
   
//     <div className="bg-black">
//        <div className="px-2 py-5">
//           <div className="flex justify-center">
//           <Image
//                 src={contenItem.img}
//                 width={100}
//                 height={50}
//                 alt="Picture of the author "
//             />
//           </div>
//            <div className="text-white">
//            <h1 className="text-md font-semibold text-[#F68921]">{contenItem.label}</h1>
//             <p className="break-all text-xs">{contenItem.heading}</p>
//             <div className="flex mt-2 gap-3">
//             <IoShieldCheckmark className="text-[#F68921] -mt-6 text-[72px]"/>
//             <p className="break-all text-sm">{contenItem.title_one}</p>
//             </div>
//             <div className="flex  gap-3 mt-2">
//             <IoShieldCheckmark className="text-[#F68921] -mt-6 text-[72px]"/>
//             <p className="break-all text-sm">{contenItem.title_two}</p>
//             </div>
//            </div>
//         </div>
//     </div>
//     );
// };

// export default DomainDetailsMobileViewPage;




import { IoShieldCheckmark } from "react-icons/io5";
import Image from "next/image";

// Function to fetch the tabs data
async function fetchTabs() {
    const response = await fetch('https://admin.pnhit.pnhbd.com/api/products');
    if (!response.ok) {
        throw new Error('Failed to fetch data');
    }
    return response.json();
}

export async function generateMetadata({ params }) {
    return {
        title: 'Product Page',
        description: "Generated by create Service Page",
    };
}

export async function generateStaticParams() {
    const tabs = await fetchTabs(); // Fetch the tabs data
    const contenId = tabs.map((tab) => ({ id: tab.id.toString() }));
    return contenId;
}

const DomainDetailsMobileViewPage = async ({ params }) => {
    const tabs = await fetchTabs(); // Fetch the tabs data
    const contenItem = tabs.find((item) => item.id == params.id);

    if (!contenItem) {
        return <div>Content not found</div>;
    }

    return (
        <div className="bg-black">
            <div className="px-2 py-5">
                <div className="flex justify-center">
                    <Image
                        src={contenItem.image}
                        width={100}
                        height={50}
                        alt={contenItem.label}
                    />
                </div>
                <div className="text-white">
                    <h1 className="text-md font-semibold text-[#F68921]">{contenItem.icon}</h1>
                    <p className="break-all text-xs">{contenItem.title}</p>
                    <div className="flex mt-2 gap-3">
                        <IoShieldCheckmark className="text-[#F68921] -mt-6 text-[72px]" />
                        <p className="break-all text-sm">{contenItem.title}</p>
                    </div>
                    <div className="flex gap-3 mt-2">
                        <IoShieldCheckmark className="text-[#F68921] -mt-6 text-[72px]" />
                        <p className="break-all text-sm">{contenItem.desp}</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default DomainDetailsMobileViewPage;
