// import BlogDetails from '@/components/BlogDetail';
// import blogsData from '@/data/blogData';  

// export async function generateMetadata({ params }) {
//   return {
//     title: 'Blog Post Page',
//     description: "Generated by create About Page",
//   }
// }

// export async function generateStaticParams() {
//   const blogIds = blogsData.map(blog => ({ id: blog.id.toString() }));
//   return blogIds;
// }

// const BlogDetailsPage = () => {
//   return (
//     <BlogDetails />
//   );
// };

// export default BlogDetailsPage;






import BlogDetails from '@/components/BlogDetail';

// Fetch the blog data from the API
async function fetchBlogsData() {
  const response = await fetch('https://admin.pnhit.pnhbd.com/api/blogs');
  return response.json();
}

export async function generateMetadata({ params }) {
  return {
    title: 'Blog Post Page',
    description: "Generated by create About Page",
  };
}

export async function generateStaticParams() {
  const blogs = await fetchBlogsData(); // Fetch blog data here
  const blogIds = blogs.map(blog => ({ id: blog.id.toString() }));
  return blogIds;
}

const BlogDetailsPage = async ({ params }) => {
  const { id } = params;
  const blogs = await fetchBlogsData(); // Fetch blog data here
  const blog = blogs.find(blog => blog.id.toString() === id);

  if (!blog) {
    return <div>Blog not found</div>;
  }

  return (
    <BlogDetails blogs={blogs} id={parseInt(id, 10)} />
  );
};

export default BlogDetailsPage;
