import React from "react";
import PropTypes from "prop-types";
import { FaArrowRight, FaChevronRight } from "react-icons/fa6";
import Link from "next/link";
import blogs from '../../data/blogData'
import NextNumber from "@/components/NextAndPrevNumber";

// or Dynamic metadata
export async function generateMetadata({ params }) {
  return {
    title: 'Blog Page',
    description: "Generated by create Blog Page",
  }
}


const BlogItem = ({ blog }) => {
  const { id, title, description, author, date, image } = blog;

  return (
    <article className="shadow-lg bg-white dark:shadow-none dark:bg-[#1E2735] rounded overflow-hidden h-full">
      <img src={image} alt={title} className="h-auto w-full" />
      <div className="p-3 pb-8 md:p-6 md:pb-5">
        <h4 className="font-medium text-2xl leading-7 mb-2">{title}</h4>
        <p>
          <span className="ml-2">
            By
            <a href="#!" className="text-[#F68921] opacity-70">
              {author}
            </a>
          </span>
          <span>
            At <span>{date}</span>
          </span>
        </p>
        <p className="opacity-60 mt-3 mb-8">{description}</p>
        <div className="flex items-center cursor-pointer">
          <Link href={`/blog/${id}`} className="bg-transparent hover:text-[#F68921] pt-2.5 px-5 transition">
            Read More
          </Link>
          <FaArrowRight  className="text-[#F68921]"/>
        </div>
      </div>
    </article>
  );
};

BlogItem.propTypes = {
  blog: PropTypes.object.isRequired,
};

const BlogPage = () => {
  return (
    <section className="ezy__blog2 light pb-14 text-stone-800 dark:text-white bg-white dark:bg-[#0b1727] overflow-hidden">
      <div className="relative w-full">
        <img
          src="/img/bg.jpg"
          alt=""
          className="h-[430px] w-full object-cover"
        />
        <div className="py-4 flex justify-center items-center gap-4 px-5 absolute inset-0 flex justify-center items-center text-white text-2xl font-bold">
          <div>
          <Link href="/" className="hover:text-[#F68921] pt-2">
              Home
            </Link>
          </div>
          <div>
            <FaChevronRight />
          </div>
          <div>
          <Link href="/blog" className="text-[#F68921] pt-2">
              Blog
            </Link>
          </div>
        </div>
      </div>

      <div className="container py-10 px- md:px-8 xl:px-32">
        <article>
          <div className="grid grid-cols-12 items-center gap-6">
            <div className="col-span-12 lg:col-span-7">
              <img
                src="https://cdn.easyfrontend.com/pictures/blog/blog_4.jpg"
                alt=""
                className="max-w-full h-auto rounded"
              />
            </div>
            <div className="col-span-12 lg:col-span-5">
              <div className="mt-6 lg:mt-0 lg:pl-6">
                <h4 className="font-medium text-2xl md:text-[40px] md:leading-[50px] mb-2 break-all">
                A business title refers to a designation or position within an organization.
                </h4>
                <p className="md:text-lg opacity-60 mt-3 mb-6 break-all">
                A business blog is one of the most cost-effective and easiest ways to promote your business. Done right, it can drive traffic to your website, increase your sales, establish you as an authority in your industry and also help you to reach new markets. Unfortunately, many small businesses are yet to wake up to the benefits of this tool. Valid reasons range from lack of time for writing the blog posts to a lack of ideas for quality posts. Here are my top tips for writing and building a successful business blog.
                </p>
                <div className="text-base leading-5 flex items-center">
                  <div className="mr-2">
                    <img
                      src="https://cdn.easyfrontend.com/pictures/testimonial/testimonial_square_3.jpeg"
                      alt=""
                      className="h-auto max-w-full rounded-full border border-border"
                      width="47"
                    />
                  </div>
                  <div className="opacity-80">
                    <p>
                      By<b> Alan Bell</b>
                    </p>
                    <p className="text-sm opacity-75">August 10th, 2020</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </article>
        <div className="grid grid-cols-12 justify-center"></div>
        <div className="grid grid-cols-12 mt-12 gap-6">
          {blogs.map((blog, i) => (
            <div className="col-span-12 md:col-span-6 lg:col-span-4" key={i}>
              <BlogItem blog={blog} />
            </div>
          ))}
        </div>
      </div>
      <NextNumber/>
    </section>
  );
};

export default BlogPage;
